### ISSUE TITLE
How do we build data-generator-x.x.x.jar?

### ISSUE THREAD

**Issue by sureddy** [openmhealth/sample-data-generator#3]
Tried building sample-data-generator using ./gradlew build. Build went successfully but i can't find the data-generator jar file.

**Comment by emersonf** [comment]
It's called `backend.jar`, since the intent was for there to be a frontend at some point. The JAR is available in `./backend/build/libs/backend-1.0.0.jar`.

I'll close this when I update the README.

**Comment by sureddy** [comment]
@emersonf thank you. That worked.
